FROM nextcloud:fpm-alpine
RUN sed -i "s@^pm.max_children.*@pm.max_children = 16@" /usr/local/etc/php-fpm.d/www.conf && \
    sed -i "s@^pm.start_servers.*@pm.start_servers = 2@" /usr/local/etc/php-fpm.d/www.conf && \
    sed -i "s@^pm.min_spare_servers.*@pm.min_spare_servers = 2@" /usr/local/etc/php-fpm.d/www.conf && \
    sed -i "s@^pm.max_spare_servers.*@pm.max_spare_servers = 12@" /usr/local/etc/php-fpm.d/www.conf && \
    echo "<?php \$CONFIG = array ( 'overwriteprotocol' => 'https', );" > /usr/src/nextcloud/config/config.php